name: Build-and-Test-CLANG-MacOS

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest clang compiler.
      run: |
            brew install llvm

    - name: Install Seaborn
      run: |
            pip install seaborn

    - name: Install Nasm.
      run: |
            brew install nasm

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           sudo cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      run: |
           /Users/runner/work/json_performance/json_performance/build/${{matrix.build_type}}/json_performance
      continue-on-error: true
      